version: "3.1"

services:
  web:
    build:
      context: flaskServer

    stop_signal: SIGINT
    ports:
        - '1234:1234'
  db:
    image: postgres
    volumes:
      - ./SQLServer/DBDump.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_USER=COSU
      - POSTGRES_PASSWORD=COSULabs
      - POSTGRES_DB=db
  ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=B0bBoY25876 #optional
      - USER_NAME=bob #optional
    ports:
      - 25:2222
    restart: unless-stopped