version: "3.1"

services:
  web:
    build:
      context: flaskServer

    stop_signal: SIGINT
    ports:
        - '1234:1234'
  db:
    build: ./SQLServer
    restart: always
    
    environment:
      POSTGRES_PASSWORD: COSULabs