version: "3.1"

services:
  web:
    build:
      context: flaskServer

    stop_signal: SIGINT
    ports:
        - '1234:1234'
  db:
    image: postgres
    volumes:
      - ./SQLServer/DBDump.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_USER=COSU
      - POSTGRES_PASSWORD=COSULabs
      - POSTGRES_DB=db
  ssh:
    build:
      context: sshServer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=B0bBoY25876 #optional
      - USER_NAME=bob #optional
    ports:
      - 2222:2222
    restart: unless-stopped
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: bob
      FTP_USER_PASS: bob1234
      FTP_USER_HOME: /home/bob
    restart: always
  # vsftpd:
  #   container_name: vsftpd
  #   image: wildscamp/vsftpd
  #   hostname: vsftpd
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #   environment:
  #     PASV_ADDRESS: 192.168.99.100
  #     PASV_MIN_PORT: 30000
  #     PASV_MAX_PORT: 30009
  #     VSFTPD_USER_1: 'bob:bob1234::'
  #     VSFTPD_USER_2: 'alice:sexygurl::'
  #     VSFTPD_USER_3: 'olroc:gigemAgs!::'