FROM python

WORKDIR /app

RUN pip3 install flask
RUN pip3 install psycopg2

RUN mkdir templates

COPY templates/index.html ./templates/
COPY static/API.txt .

COPY app.py .



EXPOSE 1234

ENV FLASK_APP=app
CMD python3 app.py
