FROM python

WORKDIR /app

RUN mkdir templates

COPY index.html ./templates/
COPY static/API.txt .

COPY app.py .

RUN pip3 install flask
RUN pip3 install psycopg2

EXPOSE 1234

ENV FLASK_APP=app
CMD python3 app.py
