FROM python

WORKDIR /app

RUN pip3 install flask
RUN pip3 install psycopg2

RUN mkdir templates

COPY templates/index.html ./templates/
COPY static/API.txt ./static/

COPY app.py .

EXPOSE 1234

ENV FLASK_APP=app
ENV PGPASS=COSULabs
ENTRYPOINT ["flask","run","--host=0.0.0.0","--port=1234"]
