
FROM gcc:latest

COPY adminServer.c .
COPY flag2.txt .
COPY adminwatchdog.c .

ENV ADMINPASS=password
ENV ADMINFLAG=flag{0v3rfl0w}

RUN gcc adminServer.c -o adminServer
RUN gcc adminwatchdog.c -o adminwatchdog

RUN chmod 777 adminServer
RUN chmod 777 adminwatchdog
RUN chmod 777 adminDumb

ENTRYPOINT ["./adminwatchdog"]