# sudo docker build -t system_health_check .
# sudo docker run -d -p 1024:1024 --rm -it system_health_check

FROM gcc:latest

COPY adminserver .
COPY flag2.txt .
COPY adminwatchdog .

ENV ADMINPASS=password
ENV ADMINFLAG=flag{0v3rfl0w}

RUN chmod 777 adminserver
RUN chmod 777 adminwatchdog

# CMD ./adminwatchdog
ENTRYPOINT ["tail", "-f", "/dev/null"]